// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: beer.proto at 106:1
package beer.hapibrew.beerxml2proto.proto;

import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum MiscType implements WireEnum {
  SPICE(0),

  FINING(1),

  WATER_AGENT(2),

  HERB(3),

  FLAVOR(4),

  OTHER(5);

  public static final ProtoAdapter<MiscType> ADAPTER = ProtoAdapter.newEnumAdapter(MiscType.class);

  private final int value;

  MiscType(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static MiscType fromValue(int value) {
    switch (value) {
      case 0: return SPICE;
      case 1: return FINING;
      case 2: return WATER_AGENT;
      case 3: return HERB;
      case 4: return FLAVOR;
      case 5: return OTHER;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }
}
