// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: beer.proto at 114:1
package beer.hapibrew.beerxml2proto.proto;

import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum MiscUse implements WireEnum {
  BOIL(0),

  MASH(1),

  PRIMARY(2),

  SECONDARY(3),

  BOTTLING(4);

  public static final ProtoAdapter<MiscUse> ADAPTER = ProtoAdapter.newEnumAdapter(MiscUse.class);

  private final int value;

  MiscUse(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static MiscUse fromValue(int value) {
    switch (value) {
      case 0: return BOIL;
      case 1: return MASH;
      case 2: return PRIMARY;
      case 3: return SECONDARY;
      case 4: return BOTTLING;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }
}
