// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: beer.proto at 5:1
package beer.hapibrew.beerxml2proto.proto;

import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum RecipeType implements WireEnum {
  ALL_GRAIN(0),

  PARTIAL_MASH(1),

  EXTRACT(2);

  public static final ProtoAdapter<RecipeType> ADAPTER = ProtoAdapter.newEnumAdapter(RecipeType.class);

  private final int value;

  RecipeType(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static RecipeType fromValue(int value) {
    switch (value) {
      case 0: return ALL_GRAIN;
      case 1: return PARTIAL_MASH;
      case 2: return EXTRACT;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }
}
