// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: beer.proto at 45:1
package beer.hapibrew.beerxml2proto.proto;

import android.os.Parcelable;
import android.support.annotation.Nullable;
import com.squareup.wire.AndroidMessage;
import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Double;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class Style extends AndroidMessage<Style, Style.Builder> {
  public static final ProtoAdapter<Style> ADAPTER = new ProtoAdapter_Style();

  public static final Parcelable.Creator<Style> CREATOR = AndroidMessage.newCreator(ADAPTER);

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_NAME = "";

  public static final Integer DEFAULT_VERSION = 1;

  public static final String DEFAULT_CATEGORY = "";

  public static final String DEFAULT_CATEGORY_NUMBER = "";

  public static final String DEFAULT_STYLE_LETTER = "";

  public static final String DEFAULT_STYLE_GUIDE = "";

  public static final StyleType DEFAULT_TYPE = StyleType.LAGER;

  public static final Double DEFAULT_OG_MIN = 1.000d;

  public static final Double DEFAULT_OG_MAX = 1.160d;

  public static final Double DEFAULT_FG_MIN = 1.000d;

  public static final Double DEFAULT_FG_MAX = 1.160d;

  public static final Double DEFAULT_ABV_MIN = 0d;

  public static final Double DEFAULT_ABV_MAX = 15d;

  public static final Double DEFAULT_SRM_MIN = 0d;

  public static final Double DEFAULT_SRM_MAX = 40d;

  public static final Double DEFAULT_IBU_MIN = 0d;

  public static final Double DEFAULT_IBU_MAX = 120d;

  public static final String DEFAULT_NOTES = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  @Nullable
  public final String name;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  @Nullable
  public final Integer version;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  @Nullable
  public final String category;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  @Nullable
  public final String category_number;

  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  @Nullable
  public final String style_letter;

  @WireField(
      tag = 6,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  @Nullable
  public final String style_guide;

  @WireField(
      tag = 7,
      adapter = "beer.hapibrew.beerxml2proto.proto.StyleType#ADAPTER"
  )
  @Nullable
  public final StyleType type;

  @WireField(
      tag = 8,
      adapter = "com.squareup.wire.ProtoAdapter#DOUBLE"
  )
  @Nullable
  public final Double og_min;

  @WireField(
      tag = 9,
      adapter = "com.squareup.wire.ProtoAdapter#DOUBLE"
  )
  @Nullable
  public final Double og_max;

  @WireField(
      tag = 10,
      adapter = "com.squareup.wire.ProtoAdapter#DOUBLE"
  )
  @Nullable
  public final Double fg_min;

  @WireField(
      tag = 11,
      adapter = "com.squareup.wire.ProtoAdapter#DOUBLE"
  )
  @Nullable
  public final Double fg_max;

  @WireField(
      tag = 12,
      adapter = "com.squareup.wire.ProtoAdapter#DOUBLE"
  )
  @Nullable
  public final Double abv_min;

  @WireField(
      tag = 13,
      adapter = "com.squareup.wire.ProtoAdapter#DOUBLE"
  )
  @Nullable
  public final Double abv_max;

  @WireField(
      tag = 14,
      adapter = "com.squareup.wire.ProtoAdapter#DOUBLE"
  )
  @Nullable
  public final Double srm_min;

  @WireField(
      tag = 15,
      adapter = "com.squareup.wire.ProtoAdapter#DOUBLE"
  )
  @Nullable
  public final Double srm_max;

  @WireField(
      tag = 16,
      adapter = "com.squareup.wire.ProtoAdapter#DOUBLE"
  )
  @Nullable
  public final Double ibu_min;

  @WireField(
      tag = 17,
      adapter = "com.squareup.wire.ProtoAdapter#DOUBLE"
  )
  @Nullable
  public final Double ibu_max;

  @WireField(
      tag = 18,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  @Nullable
  public final String notes;

  public Style(@Nullable String name, @Nullable Integer version, @Nullable String category, @Nullable String category_number, @Nullable String style_letter, @Nullable String style_guide, @Nullable StyleType type, @Nullable Double og_min, @Nullable Double og_max, @Nullable Double fg_min, @Nullable Double fg_max, @Nullable Double abv_min, @Nullable Double abv_max, @Nullable Double srm_min, @Nullable Double srm_max, @Nullable Double ibu_min, @Nullable Double ibu_max, @Nullable String notes) {
    this(name, version, category, category_number, style_letter, style_guide, type, og_min, og_max, fg_min, fg_max, abv_min, abv_max, srm_min, srm_max, ibu_min, ibu_max, notes, ByteString.EMPTY);
  }

  public Style(@Nullable String name, @Nullable Integer version, @Nullable String category, @Nullable String category_number, @Nullable String style_letter, @Nullable String style_guide, @Nullable StyleType type, @Nullable Double og_min, @Nullable Double og_max, @Nullable Double fg_min, @Nullable Double fg_max, @Nullable Double abv_min, @Nullable Double abv_max, @Nullable Double srm_min, @Nullable Double srm_max, @Nullable Double ibu_min, @Nullable Double ibu_max, @Nullable String notes, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.name = name;
    this.version = version;
    this.category = category;
    this.category_number = category_number;
    this.style_letter = style_letter;
    this.style_guide = style_guide;
    this.type = type;
    this.og_min = og_min;
    this.og_max = og_max;
    this.fg_min = fg_min;
    this.fg_max = fg_max;
    this.abv_min = abv_min;
    this.abv_max = abv_max;
    this.srm_min = srm_min;
    this.srm_max = srm_max;
    this.ibu_min = ibu_min;
    this.ibu_max = ibu_max;
    this.notes = notes;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.name = name;
    builder.version = version;
    builder.category = category;
    builder.category_number = category_number;
    builder.style_letter = style_letter;
    builder.style_guide = style_guide;
    builder.type = type;
    builder.og_min = og_min;
    builder.og_max = og_max;
    builder.fg_min = fg_min;
    builder.fg_max = fg_max;
    builder.abv_min = abv_min;
    builder.abv_max = abv_max;
    builder.srm_min = srm_min;
    builder.srm_max = srm_max;
    builder.ibu_min = ibu_min;
    builder.ibu_max = ibu_max;
    builder.notes = notes;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Style)) return false;
    Style o = (Style) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(name, o.name)
        && Internal.equals(version, o.version)
        && Internal.equals(category, o.category)
        && Internal.equals(category_number, o.category_number)
        && Internal.equals(style_letter, o.style_letter)
        && Internal.equals(style_guide, o.style_guide)
        && Internal.equals(type, o.type)
        && Internal.equals(og_min, o.og_min)
        && Internal.equals(og_max, o.og_max)
        && Internal.equals(fg_min, o.fg_min)
        && Internal.equals(fg_max, o.fg_max)
        && Internal.equals(abv_min, o.abv_min)
        && Internal.equals(abv_max, o.abv_max)
        && Internal.equals(srm_min, o.srm_min)
        && Internal.equals(srm_max, o.srm_max)
        && Internal.equals(ibu_min, o.ibu_min)
        && Internal.equals(ibu_max, o.ibu_max)
        && Internal.equals(notes, o.notes);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (name != null ? name.hashCode() : 0);
      result = result * 37 + (version != null ? version.hashCode() : 0);
      result = result * 37 + (category != null ? category.hashCode() : 0);
      result = result * 37 + (category_number != null ? category_number.hashCode() : 0);
      result = result * 37 + (style_letter != null ? style_letter.hashCode() : 0);
      result = result * 37 + (style_guide != null ? style_guide.hashCode() : 0);
      result = result * 37 + (type != null ? type.hashCode() : 0);
      result = result * 37 + (og_min != null ? og_min.hashCode() : 0);
      result = result * 37 + (og_max != null ? og_max.hashCode() : 0);
      result = result * 37 + (fg_min != null ? fg_min.hashCode() : 0);
      result = result * 37 + (fg_max != null ? fg_max.hashCode() : 0);
      result = result * 37 + (abv_min != null ? abv_min.hashCode() : 0);
      result = result * 37 + (abv_max != null ? abv_max.hashCode() : 0);
      result = result * 37 + (srm_min != null ? srm_min.hashCode() : 0);
      result = result * 37 + (srm_max != null ? srm_max.hashCode() : 0);
      result = result * 37 + (ibu_min != null ? ibu_min.hashCode() : 0);
      result = result * 37 + (ibu_max != null ? ibu_max.hashCode() : 0);
      result = result * 37 + (notes != null ? notes.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (name != null) builder.append(", name=").append(name);
    if (version != null) builder.append(", version=").append(version);
    if (category != null) builder.append(", category=").append(category);
    if (category_number != null) builder.append(", category_number=").append(category_number);
    if (style_letter != null) builder.append(", style_letter=").append(style_letter);
    if (style_guide != null) builder.append(", style_guide=").append(style_guide);
    if (type != null) builder.append(", type=").append(type);
    if (og_min != null) builder.append(", og_min=").append(og_min);
    if (og_max != null) builder.append(", og_max=").append(og_max);
    if (fg_min != null) builder.append(", fg_min=").append(fg_min);
    if (fg_max != null) builder.append(", fg_max=").append(fg_max);
    if (abv_min != null) builder.append(", abv_min=").append(abv_min);
    if (abv_max != null) builder.append(", abv_max=").append(abv_max);
    if (srm_min != null) builder.append(", srm_min=").append(srm_min);
    if (srm_max != null) builder.append(", srm_max=").append(srm_max);
    if (ibu_min != null) builder.append(", ibu_min=").append(ibu_min);
    if (ibu_max != null) builder.append(", ibu_max=").append(ibu_max);
    if (notes != null) builder.append(", notes=").append(notes);
    return builder.replace(0, 2, "Style{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<Style, Builder> {
    public String name;

    public Integer version;

    public String category;

    public String category_number;

    public String style_letter;

    public String style_guide;

    public StyleType type;

    public Double og_min;

    public Double og_max;

    public Double fg_min;

    public Double fg_max;

    public Double abv_min;

    public Double abv_max;

    public Double srm_min;

    public Double srm_max;

    public Double ibu_min;

    public Double ibu_max;

    public String notes;

    public Builder() {
    }

    public Builder name(String name) {
      this.name = name;
      return this;
    }

    public Builder version(Integer version) {
      this.version = version;
      return this;
    }

    public Builder category(String category) {
      this.category = category;
      return this;
    }

    public Builder category_number(String category_number) {
      this.category_number = category_number;
      return this;
    }

    public Builder style_letter(String style_letter) {
      this.style_letter = style_letter;
      return this;
    }

    public Builder style_guide(String style_guide) {
      this.style_guide = style_guide;
      return this;
    }

    public Builder type(StyleType type) {
      this.type = type;
      return this;
    }

    public Builder og_min(Double og_min) {
      this.og_min = og_min;
      return this;
    }

    public Builder og_max(Double og_max) {
      this.og_max = og_max;
      return this;
    }

    public Builder fg_min(Double fg_min) {
      this.fg_min = fg_min;
      return this;
    }

    public Builder fg_max(Double fg_max) {
      this.fg_max = fg_max;
      return this;
    }

    public Builder abv_min(Double abv_min) {
      this.abv_min = abv_min;
      return this;
    }

    public Builder abv_max(Double abv_max) {
      this.abv_max = abv_max;
      return this;
    }

    public Builder srm_min(Double srm_min) {
      this.srm_min = srm_min;
      return this;
    }

    public Builder srm_max(Double srm_max) {
      this.srm_max = srm_max;
      return this;
    }

    public Builder ibu_min(Double ibu_min) {
      this.ibu_min = ibu_min;
      return this;
    }

    public Builder ibu_max(Double ibu_max) {
      this.ibu_max = ibu_max;
      return this;
    }

    public Builder notes(String notes) {
      this.notes = notes;
      return this;
    }

    @Override
    public Style build() {
      return new Style(name, version, category, category_number, style_letter, style_guide, type, og_min, og_max, fg_min, fg_max, abv_min, abv_max, srm_min, srm_max, ibu_min, ibu_max, notes, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_Style extends ProtoAdapter<Style> {
    ProtoAdapter_Style() {
      super(FieldEncoding.LENGTH_DELIMITED, Style.class);
    }

    @Override
    public int encodedSize(Style value) {
      return (value.name != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.name) : 0)
          + (value.version != null ? ProtoAdapter.INT32.encodedSizeWithTag(2, value.version) : 0)
          + (value.category != null ? ProtoAdapter.STRING.encodedSizeWithTag(3, value.category) : 0)
          + (value.category_number != null ? ProtoAdapter.STRING.encodedSizeWithTag(4, value.category_number) : 0)
          + (value.style_letter != null ? ProtoAdapter.STRING.encodedSizeWithTag(5, value.style_letter) : 0)
          + (value.style_guide != null ? ProtoAdapter.STRING.encodedSizeWithTag(6, value.style_guide) : 0)
          + (value.type != null ? StyleType.ADAPTER.encodedSizeWithTag(7, value.type) : 0)
          + (value.og_min != null ? ProtoAdapter.DOUBLE.encodedSizeWithTag(8, value.og_min) : 0)
          + (value.og_max != null ? ProtoAdapter.DOUBLE.encodedSizeWithTag(9, value.og_max) : 0)
          + (value.fg_min != null ? ProtoAdapter.DOUBLE.encodedSizeWithTag(10, value.fg_min) : 0)
          + (value.fg_max != null ? ProtoAdapter.DOUBLE.encodedSizeWithTag(11, value.fg_max) : 0)
          + (value.abv_min != null ? ProtoAdapter.DOUBLE.encodedSizeWithTag(12, value.abv_min) : 0)
          + (value.abv_max != null ? ProtoAdapter.DOUBLE.encodedSizeWithTag(13, value.abv_max) : 0)
          + (value.srm_min != null ? ProtoAdapter.DOUBLE.encodedSizeWithTag(14, value.srm_min) : 0)
          + (value.srm_max != null ? ProtoAdapter.DOUBLE.encodedSizeWithTag(15, value.srm_max) : 0)
          + (value.ibu_min != null ? ProtoAdapter.DOUBLE.encodedSizeWithTag(16, value.ibu_min) : 0)
          + (value.ibu_max != null ? ProtoAdapter.DOUBLE.encodedSizeWithTag(17, value.ibu_max) : 0)
          + (value.notes != null ? ProtoAdapter.STRING.encodedSizeWithTag(18, value.notes) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, Style value) throws IOException {
      if (value.name != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.name);
      if (value.version != null) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.version);
      if (value.category != null) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.category);
      if (value.category_number != null) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.category_number);
      if (value.style_letter != null) ProtoAdapter.STRING.encodeWithTag(writer, 5, value.style_letter);
      if (value.style_guide != null) ProtoAdapter.STRING.encodeWithTag(writer, 6, value.style_guide);
      if (value.type != null) StyleType.ADAPTER.encodeWithTag(writer, 7, value.type);
      if (value.og_min != null) ProtoAdapter.DOUBLE.encodeWithTag(writer, 8, value.og_min);
      if (value.og_max != null) ProtoAdapter.DOUBLE.encodeWithTag(writer, 9, value.og_max);
      if (value.fg_min != null) ProtoAdapter.DOUBLE.encodeWithTag(writer, 10, value.fg_min);
      if (value.fg_max != null) ProtoAdapter.DOUBLE.encodeWithTag(writer, 11, value.fg_max);
      if (value.abv_min != null) ProtoAdapter.DOUBLE.encodeWithTag(writer, 12, value.abv_min);
      if (value.abv_max != null) ProtoAdapter.DOUBLE.encodeWithTag(writer, 13, value.abv_max);
      if (value.srm_min != null) ProtoAdapter.DOUBLE.encodeWithTag(writer, 14, value.srm_min);
      if (value.srm_max != null) ProtoAdapter.DOUBLE.encodeWithTag(writer, 15, value.srm_max);
      if (value.ibu_min != null) ProtoAdapter.DOUBLE.encodeWithTag(writer, 16, value.ibu_min);
      if (value.ibu_max != null) ProtoAdapter.DOUBLE.encodeWithTag(writer, 17, value.ibu_max);
      if (value.notes != null) ProtoAdapter.STRING.encodeWithTag(writer, 18, value.notes);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public Style decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.name(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.version(ProtoAdapter.INT32.decode(reader)); break;
          case 3: builder.category(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.category_number(ProtoAdapter.STRING.decode(reader)); break;
          case 5: builder.style_letter(ProtoAdapter.STRING.decode(reader)); break;
          case 6: builder.style_guide(ProtoAdapter.STRING.decode(reader)); break;
          case 7: {
            try {
              builder.type(StyleType.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 8: builder.og_min(ProtoAdapter.DOUBLE.decode(reader)); break;
          case 9: builder.og_max(ProtoAdapter.DOUBLE.decode(reader)); break;
          case 10: builder.fg_min(ProtoAdapter.DOUBLE.decode(reader)); break;
          case 11: builder.fg_max(ProtoAdapter.DOUBLE.decode(reader)); break;
          case 12: builder.abv_min(ProtoAdapter.DOUBLE.decode(reader)); break;
          case 13: builder.abv_max(ProtoAdapter.DOUBLE.decode(reader)); break;
          case 14: builder.srm_min(ProtoAdapter.DOUBLE.decode(reader)); break;
          case 15: builder.srm_max(ProtoAdapter.DOUBLE.decode(reader)); break;
          case 16: builder.ibu_min(ProtoAdapter.DOUBLE.decode(reader)); break;
          case 17: builder.ibu_max(ProtoAdapter.DOUBLE.decode(reader)); break;
          case 18: builder.notes(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public Style redact(Style value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
