// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: beer.proto at 140:1
package beer.hapibrew.beerxml2proto.proto;

import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum YeastForm implements WireEnum {
  LIQUID(0),

  DRY(1),

  SLANT(2),

  CULTURE(3);

  public static final ProtoAdapter<YeastForm> ADAPTER = ProtoAdapter.newEnumAdapter(YeastForm.class);

  private final int value;

  YeastForm(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static YeastForm fromValue(int value) {
    switch (value) {
      case 0: return LIQUID;
      case 1: return DRY;
      case 2: return SLANT;
      case 3: return CULTURE;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }
}
